Repository knative-portability/Kubercade, pull requests merged in 2019-08, with the labels that each got.

#1 Dev setup
  .gitignore
  Dockerfile
  README.md
  index.js
  package-lock.json
  package.json
  prettier.config.js
  src/app.ts
  src/controllers/indexController.ts
  src/routes/index.ts
  tests/index.test.ts
  tsconfig.json
  tslint.json
Labels: enhancement

#4 Write schema
  src/.schema.sql
Labels: enhancement, help wanted

#6 Set up CircleCI
  .circleci/config.yml
  package-lock.json
  package.json
  tests/index.test.ts
Labels: enhancement

#5 High score display routes
  package-lock.json
  package.json
  src/app.ts
  src/config/gameInfo.json
  src/config/gameInfoUtil.ts
  src/controllers/scoresController.ts
  src/routes/scores.ts
  tests/dummy/dummyScores.json
  tests/index.test.ts
  tsconfig.json
  views/scores.pug
Labels: enhancement

#7 Clean up package-lock.json
  package-lock.json
  package.json
Labels: cleanup

#8 Add CircleCI badge
  README.md
Labels: documentation, enhancement, tiny

#11 Create basic navigation ui
  views/index.pug
  views/js/navigation.js
  views/style.css
Labels: enhancement

#9 Nexus ui
  src/app.ts
  src/controllers/nexusController.ts
  src/routes/nexus.ts
  views/index.pug
  views/nexus.pug
  views/style.css
Labels: enhancement

#16 Set up chat skeleton
  src/app.ts
  src/controllers/chatController.ts
  src/routes/chat.ts
Labels: enhancement

#15 Fix scores displaying
  src/controllers/scoresController.ts
Labels: bug

#14 Fix SQL schema
  src/.schema.sql
Labels: bug

#12 Add route to store new high scores
  package.json
  src/app.ts
  src/controllers/scoresController.ts
  src/routes/scores.ts
Labels: enhancement

#10 Pacman static serving
  src/app.ts
  src/controllers/gameController.ts
  src/routes/games.ts
  vendor/pacman/README.md
  vendor/pacman/css/Quadrit.ttf
  vendor/pacman/css/pacman-home.css
  vendor/pacman/css/pacman.css
  vendor/pacman/img/github.png
  vendor/pacman/img/move-down-big.png
  vendor/pacman/img/move-down.png
  vendor/pacman/img/move-left-big.png
  vendor/pacman/img/move-left.png
  vendor/pacman/img/move-right-big.png
  vendor/pacman/img/move-right.png
  vendor/pacman/img/move-up-big.png
  vendor/pacman/img/move-up.png
  vendor/pacman/img/preview.png
  vendor/pacman/img/sound-off.png
  vendor/pacman/img/sound-on.png
  vendor/pacman/index.html
  vendor/pacman/js/board.js
  vendor/pacman/js/bubbles.js
  vendor/pacman/js/fruits.js
  vendor/pacman/js/game.js
  vendor/pacman/js/ghosts.js
  vendor/pacman/js/home.js
  vendor/pacman/js/jquery-buzz.js
  vendor/pacman/js/jquery-mobile.js
  vendor/pacman/js/jquery.js
  vendor/pacman/js/pacman.js
  vendor/pacman/js/paths.js
  vendor/pacman/js/sound.js
  vendor/pacman/js/tools.js
  vendor/pacman/sound/die.mp3
  vendor/pacman/sound/eat-fruit.mp3
  vendor/pacman/sound/eat-ghost.mp3
  vendor/pacman/sound/eat-pill.mp3
  vendor/pacman/sound/eating.mp3
  vendor/pacman/sound/extra-life.mp3
  vendor/pacman/sound/ghost-eaten.mp3
  vendor/pacman/sound/ready.mp3
  vendor/pacman/sound/siren.mp3
  vendor/pacman/sound/waza.mp3
Labels: enhancement, help wanted

#13 Improve prettiness
  public/images/kubercade logo.png
  src/app.ts
  views/index.pug
  views/nexus.pug
  views/scores.pug
  views/style.css
Labels: cleanup, enhancement

#17 Improve scores display
  views/js/randomColorsForScores.js
  views/scores.pug
  views/style.css
Labels: enhancement

#18 UI for posting score
  src/app.ts
  views/index.pug
  views/js/navigation.js
  views/js/submitScore.js
Labels: enhancement

#19 Create chat UI
  views/index.pug
  views/js/chatControl.js
  views/style.css
Labels: enhancement

#21 Style game nexus
  public/images/pacman_thumbnail.png
  views/nexus.pug
  views/style.css
Labels: enhancement

#23 Es6 front end refactor
  views/js/chatControl.js
  views/js/navigation.js
  views/js/randomColorsForScores.js
  views/js/submitScore.js
Labels: cleanup

#26 Favicon
  package.json
  public/images/favicon.ico
  views/index.pug
Labels: enhancement

#22 Connect chat UI to endpoints
  package.json
  src/.schema.sql
  src/config/gameInfoUtil.ts
  src/config/timeUtil.ts
  src/controllers/chatController.ts
  src/controllers/scoresController.ts
  src/routes/chat.ts
  views/index.pug
  views/js/chatControl.js
  views/js/navigation.js
  views/scores.pug
Labels: enhancement

#24 Trigger score submit on game end
  views/index.pug
  views/js/navigation.js
  views/js/submitScore.js
Labels: enhancement, help wanted

#25 Responsive design
  views/index.pug
  views/style.css
Labels: enhancement

#29 Make pug template game links dynamic
  src/controllers/indexController.ts
  views/index.pug
  views/nexus.pug
Labels: cleanup, enhancement

#30 Empty chat indicator
  views/index.pug
  views/js/chatControl.js
  views/style.css
Labels: enhancement

#27 High score filter
  views/js/filterScores.js
  views/scores.pug
  views/style.css
Labels: enhancement

#28 Hide chat
  views/index.pug
  views/js/chatControl.js
  views/style.css
Labels: enhancement

#31 Sanitize inputs
  package-lock.json
  package.json
  src/controllers/chatController.ts
  src/controllers/scoresController.ts
  src/routes/chat.ts
  src/routes/scores.ts
  views/js/chatControl.js
Labels: bug

#36 Remove extra quote
  views/index.pug
Labels: bug

#51 Fix Deploy on Google Cloud button for demo
  app.json
Labels: bug

#52 Fix documentation
  vendor/minesweeper/ATTRIBUTION.md
  vendor/pacman/ATTRIBUTION.md
  vendor/pacman/LICENSE
  vendor/pacman/README.md
Labels: documentation
